project:
  type: website
  output-dir: docs

website:
  title: "EcoDataScience"
  # site-url: https://ecodatascience.github.io/
  favicon: images/ecodatasci_logo.png  
  
  page-footer: 
    right: "This page is built with ❤️ and [Quarto](https://quarto.org/)"
    left: "&copy; CC-By EcoDataScience"
  
  
 
  navbar:
    logo: images/eds_final_hex.png
    # href: https://openscapes.org ## add link to website when ready
    right:
    # - text: "Home"
    #   href: index.html
    - text: "who we are"
      href: who-we-are.qmd
    - text: "events"
      href: events.qmd
    - text: "community"
      href: community-resources.qmd
    - text: "new to EDS?"
      href: welcome.qmd
    - icon: github
      href: https://github.com/ecodatascience
    - icon: twitter
      href: https://twitter.com/ecodatasci


format:
  html:
    page-layout: full
    sidebar: false
    theme: [flatly, theme.scss]
    css: styles.css
    mainfont: Montserrat
    toc: true
    toc-location: left

