---
title: "community - resources"
---

EcoDataScience exists within a rich culture of organizations dedicated to learning and practicing open, transparent, repeatable data science.  While our members span the globe, our main focus is on serving the UCSB community, so many of the resources here focus on the Santa Barbara area, but we have included links to parent organizations for our members who live, work, and play remotely.  Follow the links for more information, or start a discussion about these various resources in the EcoDataScience Slack workspace!

* The Carpentries ([SB org](https://www.library.ucsb.edu/carpentry-workshops) | [global org](https://carpentries.org/index.html) teaches foundational coding and data science skills to researchers worldwide.
* R-Ladies ([SB chapter](https://www.nceas.ucsb.edu/r-ladies-santa-barbara) | [global org](https://rladies.org/)) is a worldwide organization whose mission is to promote gender diversity in the R community.
* [OpenScapes](https://openscapes.org/) is an approach and a movement that helps researchers and those supporting research find each other and feel empowered to conduct data-intensive science.
* [rOpenSci](https://ropensci.org/about/) fosters a culture that values open and reproducible research using shared data and reusable software.

Descriptions for these resources come from the various websites linked.  

If you represent an organization with a similar mission, please reach out and we will include a link!
