name: Render and deploy Quarto files
on: 
  push:
  pull_request:

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Quarto
      uses: quarto-dev/quarto-actions/setup@v2
      with:
          # To install LaTeX to build PDF book 
          tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600


    - name: "Install Quarto and render"
      uses: pommevilla/quarto-render@main

    - name: "Deploy to gh-pages"
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/master'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs




#name: Render and Publish

#jobs:
 # build-deploy:
  #  runs-on: ubuntu-latest
   # steps:
    #  - name: Check out repository
     #   uses: actions/checkout@v2 
        
      #- name: Set up Quarto
       # uses: quarto-dev/quarto-actions/setup@v2
        #with:
         # # To install LaTeX to build PDF book 
          #tinytex: true 
          # uncomment below and fill to pin a version
          # version: 0.9.600
      
      # add software dependencies here

      # - name: Publish to GitHub Pages (and render)
       # uses: quarto-dev/quarto-actions/publish@v2
        #with:
         # target: gh-pages
        #env:
         # GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # this secret is always available for github actions
